name: test

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: test
        run: |
            Write-Host -Object ${{ github.event_name }}
